version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5500:5500
    container_name: kttc_social_platform_web
    restart: unless-stopped
    volumes:
      - "/mnt/nfs/rossxp/tech/social_platform:/upload"